### ISSUE TITLE
Rotten Tomatoes App Curriculum: 4 part approach

### ISSUE THREAD

**Issue by jeffreybergier** [mobilebridge/iosbridge#5]
I wanted to get everyone's opinion on new curriculum for the next iOS MobileBridge. There was a lot of feedback from the last session that the tip calculator app didn't leave enough time for the rotten tomatoes app. I definitely agree with this feedback, but I also felt like the tip calculator app is the key to understanding how the XIB/Storyboard is connected to the code. So I was thinking of solutions to this and I was going to start a new curriculum guide for instructors that had the following basic sections.

- Section 1) Understanding Interaction Paradigms on iOS
     - Emphasis that this whirlwind 6 hour session of iOS will NOT teach all of iOS. 
     - Also emphasize that a lot of the code and syntax we are just going to ignore and go with the flow. Previous feedback showed the Objective C overview was not that useful. Either the experience level of the students is such that it goes right over their heads or they already fundamentally understand the concepts and the syntax is just syntax and is not a big deal.
     - This section is off the computer. The instructor will whiteboard and show the students the basic interaction paradigms in iOS.
     - The 4 fundamental ones are probably UIViewController, UINavigationController, UITabBarController and UITableView / Controller.
- Section 2) Fundamentals of Connecting XIB/Storyboard to Code
     - In this section, the instructor will walk the students through building a UIViewController that has a button and a text field and a label. 
     - Clicking the button will take the text from the textfield and put it into the label.
     - I think this will teach the IBAction / IBOutlet / Communication paradigm taught by the tip calculator but be much faster
- Section 3) Build the UI for the Rotten Tomatoes App
     - This is where the instructor will walk the students through the concept of "Prototype" cells
     - Connect a single UILabel in the cell to a UITableViewCell subclass
     - Then changing the label in the tableViewCellForRowAtIndexPath
     - Lastly, preparing the labels and images needed for the rotten tomatoes app
- Section 4) Download the Rotten Tomatoes JSON and Parse it and Connect it to the TableView
    - Use NSURLSession to download the rotten tomatoes JSON file
    - Parse it with NSJSONSerialization (see the dictionary in the debugger)
    - Learn how to take this array and put it into tableViewCellForRowAtIndexPath to populate the TableView
    - If we make it this far, show how to download the images with NSURLSession for the cells (this is tricky because of the way iOS recycles cells).

**Comment by ultrasaurus** [comment]
With the caveat that I don't have experience with the prior RotenTomatoes approach -- I like this approach.  To whatever extent you could build a tiny app in sections (1) and (2) that would be directly applicable (or part of?) the app you build in section 3 & 4, I think that would be helpful.

This may be too late for feedback (if so, please feel free to disregard this), but I wonder if #2 was first with a single view app, it might be easier for people who have written code in other environments to feel comfortable with what is going on.  Then you could add in the material from #1 and show how to create UINavigationController, UITabBarController, etc. by making that one view of several tabs.

**Comment by ultrasaurus** [comment]
@jeffreybergier renamed this issue so it is easier to distinguish from the other curriculum idea I added: https://github.com/mobilebridge/iosbridge/issues/6

**Comment by jeffreybergier** [comment]
Hey everyone,

I finished most of the curriculum I was planning to go over tomorrow. I could certainly use a fresh set of eyes on this. If anyone has time, could you read over it and make sure the guide makes sense, teaches the right things and has enough detail? Also, I'm a bit worried about the tone. Does it sound instructional without being condescending?

https://github.com/jeffreybergier/RottenTomatoesGuide/wiki

Thanks!
-Jeff

**Comment by jeffreybergier** [comment]
@ultrasaurus thanks for the feedback on the structure. I definitely am a little upset that part 2 has to be discarded to start part 3. The problem I was having is that its hard to understand how prototype cells work on their own. So I thought connecting UI elements to code in a "fixed" view would be the easier way to address the concept of IBActions and IBOutlets before also introducing the prototype cells.

As for order of operations, that definitely sounds like something that should be flexible. 

I'll bring these issues up at the teacher training tomorrow. These documents are definitely living documents and I'm open to suggestions and to others modifying them. I'm not sure how permissions work on Github wikis but there must be a way to allow others to edit them.

**Comment by kmolo** [comment]
Comments related to this thread which ended up on another thread:

https://github.com/mobilebridge/organizing/issues/5#issuecomment-94198457
