### ISSUE TITLE
add info about showing iPhone screen with QuickTime

### ISSUE THREAD

**Issue by ultrasaurus** [mobilebridge/iosbridge#8]
May only be available on 10.10 (Yosemite)...

Add to demonstration tips section on [wiki](https://github.com/mobilebridge/iosbridge/wiki/iOS-1-day-Weekend-Workshop)
![image](https://cloud.githubusercontent.com/assets/41906/7222063/ca93f9ee-e6b9-11e4-919b-5861f639fe0f.png)

click on the little arrow next to the record button:
![image](https://cloud.githubusercontent.com/assets/41906/7222078/481fbc72-e6ba-11e4-99ed-e4dd9a82da2d.png)

and if your phone is plugged in, then you can select it:
![image](https://cloud.githubusercontent.com/assets/41906/7222076/333d815e-e6ba-11e4-9778-a978864c7b0c.png)

**Comment by jeffreybergier** [comment]
I put this into the UI Paradigms section of the curriculum. https://github.com/mobilebridge/iosbridge-rottentomatoes/blob/master/TextForGuide/iOS-UI-Paradigms.md

**Comment by kmolo** [comment]
@ultrasaurus @jeffreybergier two questions:
- do you choose 'New Movie Recording' or 'New Screen Record' or would either work?
- do you not have to click the red 'Record' button, but instead just choose the correct device at which point the iPhone / iPad screen will appear in the display showing the live app interaction on the phone for everyone to see on the display?

**Comment by jeffreybergier** [comment]
- New Movie Recording
- The record button is only needed if you want to save what you're showing to disk for watching later.
